### ISSUE TITLE
Some errors of comment

### ISSUE THREAD

**Issue by weycen** [STMicroelectronics/stm32f0xx_hal_driver#2]
Some errors of comment in the `stm32f0xx_hal_gpio_ex.h` file.
https://github.com/STMicroelectronics/stm32f0xx_hal_driver/blob/5eeaad10dc3816830abd9b3bfd74c6974453e907/Inc/stm32f0xx_hal_gpio_ex.h#L505
https://github.com/STMicroelectronics/stm32f0xx_hal_driver/blob/5eeaad10dc3816830abd9b3bfd74c6974453e907/Inc/stm32f0xx_hal_gpio_ex.h#L519-L520
https://github.com/STMicroelectronics/stm32f0xx_hal_driver/blob/5eeaad10dc3816830abd9b3bfd74c6974453e907/Inc/stm32f0xx_hal_gpio_ex.h#L589

**Comment by ASELSTM** [comment]
Hi @weycen,

Thank you for this report. I see you have created a pull request #3 to fix the erroneous comments . Please allow me then to close this thread and to consider the pull request.

With regards,
